version: 1

enabled_features:
  auto_review: true
  post_review_summary: true
  inline_suggestions: true
  review_pull_request: true
  severity_level: true

review_comment_severity:
  critical: true
  high: true
  medium: true
  low: false

code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  max_review_comments: -1

pull_request_opened:
  summary: true
  code_review: true
  help: false